#!/usr/bin/env ruby

=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end

puts ((1...100).reduce([1,2]) { |acc| acc += [acc[-2, 2].inject(:+)]}.select {|x| x < 4000000 and x & 1 == 0}.inject(:+))
